#!/usr/bin/env bash
#
# bootstrap.sh — Generate the LiveKit server `.env` with strong random
# secrets. Refuses to overwrite an existing `.env` unless `--force` is
# passed; on `--force` it writes a timestamped backup first.
#
# Stdout is safe to log: the only secret-derived value printed is the first
# 8 characters of the API key (the "key id"). The API secret and Redis
# password are never echoed.

set -euo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log() {
  # Single-line, prefixed, no secret values. Operators can grep `[bootstrap]`.
  printf '[bootstrap] %s\n' "$1"
}

die() {
  printf '[bootstrap] ERROR: %s\n' "$1" >&2
  exit 1
}

# Trim base64 output to printable URL-safe characters (drops `=` padding and
# any stray newline). Used so the API key id is easy to copy/paste.
sanitize() {
  printf '%s' "$1" | tr -d '=+/\n'
}

# ---------------------------------------------------------------------------
# Argument parsing — only `--force` is supported.
# ---------------------------------------------------------------------------

FORCE=0
case "${1:-}" in
  "")          ;;
  --force)     FORCE=1 ;;
  -h|--help)
    cat <<'USAGE'
Usage: bootstrap.sh [--force]

  (no args)   Generate `.env` if it does not exist. Exits non-zero if it does.
  --force     Rotate secrets. Existing `.env` is backed up to `.env.bak.<ts>`.
  -h|--help   Show this message.
USAGE
    exit 0
    ;;
  *)
    die "unknown argument '$1' — see --help"
    ;;
esac

# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------

# Resolve this script's directory so the script works regardless of CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIVEKIT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${LIVEKIT_DIR}/.env"

if ! command -v openssl >/dev/null 2>&1; then
  die "openssl is required but was not found in PATH. Install it and retry."
fi

if [ -f "${ENV_FILE}" ] && [ "${FORCE}" -eq 0 ]; then
  die ".env already exists at ${ENV_FILE} — pass --force to rotate secrets."
fi

# ---------------------------------------------------------------------------
# Backup existing .env when rotating.
# ---------------------------------------------------------------------------

if [ -f "${ENV_FILE}" ] && [ "${FORCE}" -eq 1 ]; then
  TIMESTAMP="$(date +%Y%m%d%H%M%S)"
  BACKUP_FILE="${ENV_FILE}.bak.${TIMESTAMP}"
  cp "${ENV_FILE}" "${BACKUP_FILE}"
  chmod 600 "${BACKUP_FILE}"
  log "backed up previous .env to $(basename "${BACKUP_FILE}")"
fi

# ---------------------------------------------------------------------------
# Generate secrets.
# ---------------------------------------------------------------------------

log "generating LIVEKIT_API_KEY"
LIVEKIT_API_KEY="$(sanitize "$(openssl rand -base64 12)")"

log "generating LIVEKIT_API_SECRET"
LIVEKIT_API_SECRET="$(sanitize "$(openssl rand -base64 32)")"

log "generating REDIS_PASSWORD"
REDIS_PASSWORD="$(sanitize "$(openssl rand -base64 32)")"

# Default the TURN domain to `example.com`; operators edit it in `.env`
# before enabling the TURN block in `livekit.yaml`.
LIVEKIT_TURN_DOMAIN="example.com"

# ---------------------------------------------------------------------------
# Write .env atomically with mode 600.
# ---------------------------------------------------------------------------

# Restrict file mode of newly created files in this shell to 600.
umask 077

log "writing ${ENV_FILE}"
cat > "${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file. To rotate, run: bash scripts/bootstrap.sh --force
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
REDIS_PASSWORD=${REDIS_PASSWORD}
LIVEKIT_TURN_DOMAIN=${LIVEKIT_TURN_DOMAIN}
EOF

# Defensive — `umask 077` should already cover this, but be explicit.
chmod 600 "${ENV_FILE}"

# ---------------------------------------------------------------------------
# Report — print ONLY the key id (first 8 chars of the API key).
# ---------------------------------------------------------------------------

KEY_ID="$(printf '%s' "${LIVEKIT_API_KEY}" | cut -c1-8)"
log "done. new key id (first 8 chars of LIVEKIT_API_KEY): ${KEY_ID}"
log "secrets stored at ${ENV_FILE} (mode 600). Never commit this file."
